# Generated by Django 3.2.9 on 2021-11-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(db_column='department_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.department'),
            preserve_default=False,
        ),
    ]
